In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.datasets import make_classification
from sklearn.impute import SimpleImputer
import plotly.graph_objs as go
import plotly.offline as py
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
from sklearn.metrics import mean_squared_error
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import precision_score
from imblearn.under_sampling import RandomUnderSampler

In [ ]:
from sklearn import preprocessing
from collections import Counter

In [ ]:
#Loading data
from google.colab import files
uploaded = files.upload()

Saving GDM_DataDivers.xlsx to GDM_DataDivers.xlsx

In [ ]:
#storing data into a dataframe
df=pd.read_excel('GDM_DataDivers.xlsx')
# Printing data
df

,Patient_ID,systolicBP_V1,diastolicBP_V1,PulseinV1,WeightinV1,Height_cms,BMIinV1,Smoking 123,Ethnicity,PreviousGDM10 V1,...,BirthInjury,Dystocia,Antenatal_steroid_use,FetalJaundice,Total bilirubin,RR>60,SCBU,Cong malformation,Epidural,Spinal
0,1,114,58,73,59.4,169.6,20.650699,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
1,2,178,78,84,70.1,154.9,29.215625,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
2,3,123,62,79,64.9,157.8,26.063378,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
3,4,115,68,82,67.1,164.7,24.736333,3,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
4,5,116,61,92,67.5,169.9,23.383904,3,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560,596,127,72,89,57.6,159.7,22.584613,3,White,0,...,0,0,No,0,NaN,No,0,0,Yes,No
561,597,138,63,98,94.5,156.9,38.387155,1,White,0,...,0,0,No,0,NaN,No,0,0,No,Yes
562,598,115,69,81,93.1,162.6,35.213452,2,White,0,...,0,0,No,0,NaN,No,0,0,Yes,No
563,599,129,69,84,78.4,177.4,24.912014,3,White,0,...,NR,NR,NR,NR,NaN,NR,NR,0,No,NR
564,600,110,53,64,64.2,155.0,26.722164,3,White,0,...,0,0,No,0,NaN,No,0,0,Yes,No

In [ ]:
df.columns.values.tolist()

['Patient_ID',
 'systolicBP_V1',
 'diastolicBP_V1',
 'PulseinV1',
 'WeightinV1',
 'Height_cms',
 'BMIinV1',
 'Smoking 123',
 'Ethnicity',
 'PreviousGDM10 V1',
 'Chronic Illness',
 'Medications_All',
 'Age_gt_30',
 'HighRisk',
 'Screening method',
 '1st DASS score >33',
 'Gestational Age_V1',
 'EDD V1',
 'White Cell Count',
 'Platelet_V1',
 'Calcium_V1',
 'Albumin_V1',
 'U Albumin_V1',
 'U Protein_V1',
 'V1 US EDD',
 'EDDEqLMP',
 'EDDMethod',
 '25OHD value (nmol/L)_V1',
 'Caltrate',
 'Glucose_1h',
 'OGTT_0h_value',
 'OGTT_1h_value',
 'OGTT_2h_value',
 'Miscarriage after 28/40 10',
 'Withdrew after 28/40 10',
 'Delivered before 36/40',
 'Attended Visit 3',
 'Date of Visit 3',
 'HB1AC_V2',
 'WeightinV3',
 'systolicBP_V3',
 'diastolicBP_V3',
 'PulseinV3',
 '3rd visit DASS >33',
 'White Cell Count_V3',
 'Platelet_V3',
 'Calcium_V3',
 'Albumin_V3',
 'ALT_V3',
 'U Albumin_V3',
 'U Protein_V3',
 '25OHD value_V3',
 'Abdominal Circumference_V3',
 'HBA1C_V1',
 'HBA1C_V3',
 'Hemoglobin_V1',
 'Hemoglobin_V3',
 'V1 Creatinine.1',
 'V3 Creat.1',
 'ALT_V1',
 'V1 CRP.1',
 'V3 CRP.1',
 'V1 PCR.1',
 'V3 U PCR.1',
 'GA at delivery',
 'GDM Diagonised',
 'Attended_GDM_clinics',
 'Vit D Deficiency',
 'Took Vit D Supplements',
 'Nutritional counselling',
 'GlucoseTherapy',
 'On_Insulin',
 'On_Metformin',
 'GestationalHP',
 'Pre eclampsia',
 'Eclampsia',
 'Labor_Induced',
 'Caesarean',
 'Emergency',
 'Instrument_Delivery',
 'Still-birth',
 'Twins',
 'BirthWeight',
 'Twins weight',
 'Apgar_1min',
 'Apgar_3min',
 'BirthInjury',
 'Dystocia',
 'Antenatal_steroid_use',
 'FetalJaundice',
 'Total bilirubin',
 'RR>60',
 'SCBU',
 'Cong malformation',
 'Epidural',
 'Spinal']

In [ ]:
df.dtypes

Patient_ID             int64
systolicBP_V1          int64
diastolicBP_V1         int64
PulseinV1              int64
WeightinV1           float64
                      ...
RR>60                 object
SCBU                  object
Cong malformation      int64
Epidural              object
Spinal                object
Length: 96, dtype: object

In [ ]:
#checking for count of empty values in columns
df.isnull().sum()

Patient_ID           0
systolicBP_V1        0
diastolicBP_V1       0
PulseinV1            0
WeightinV1           0
                    ..
RR>60                0
SCBU                 0
Cong malformation    0
Epidural             0
Spinal               0
Length: 96, dtype: int64

In [ ]:
#checking for missing or null values
df.isnull().values.any()

True

In [ ]:
df.drop(df[df['GDM Diagonised'] == 'NR'].index, inplace = True)

In [ ]:
df

,Patient_ID,systolicBP_V1,diastolicBP_V1,PulseinV1,WeightinV1,Height_cms,BMIinV1,Smoking 123,Ethnicity,PreviousGDM10 V1,...,BirthInjury,Dystocia,Antenatal_steroid_use,FetalJaundice,Total bilirubin,RR>60,SCBU,Cong malformation,Epidural,Spinal
0,1,114,58,73,59.4,169.6,20.650699,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
1,2,178,78,84,70.1,154.9,29.215625,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
2,3,123,62,79,64.9,157.8,26.063378,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
3,4,115,68,82,67.1,164.7,24.736333,3,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
4,5,116,61,92,67.5,169.9,23.383904,3,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,595,117,74,87,56.9,160.5,22.088295,3,White,0,...,0,0,No,0,NaN,No,0,0,Yes,No
560,596,127,72,89,57.6,159.7,22.584613,3,White,0,...,0,0,No,0,NaN,No,0,0,Yes,No
561,597,138,63,98,94.5,156.9,38.387155,1,White,0,...,0,0,No,0,NaN,No,0,0,No,Yes
562,598,115,69,81,93.1,162.6,35.213452,2,White,0,...,0,0,No,0,NaN,No,0,0,Yes,No
564,600,110,53,64,64.2,155.0,26.722164,3,White,0,...,0,0,No,0,NaN,No,0,0,Yes,No

In [ ]:
df.dtypes['Vit D Deficiency']

dtype('O')

In [ ]:
#Transforming non numerical column into numerical column
from sklearn.preprocessing import LabelEncoder
for column in df.columns:
  if df[column].dtype == np.float64 :
    continue
    df[column] = LabelEncoder().fit_transform(df[column])

In [ ]:
lbl_encoder=LabelEncoder()

In [ ]:
lbl_encoder.fit_transform(df['Age_gt_30'])

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
df['Age_gt_30'] = lbl_encoder.fit_transform(df['Age_gt_30'])

In [ ]:
df['Age_gt_30'].value_counts()

1    362
0    203
Name: Age_gt_30, dtype: int64

In [ ]:
lbl_encoder.fit_transform(df['Vit D Deficiency'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
df['Vit D Deficiency'] = lbl_encoder.fit_transform(df['Vit D Deficiency'])

In [ ]:
df['Vit D Deficiency'].value_counts()

0    381
1    184
Name: Vit D Deficiency, dtype: int64

In [ ]:
df.head()

,Patient_ID,systolicBP_V1,diastolicBP_V1,PulseinV1,WeightinV1,Height_cms,BMIinV1,Smoking 123,Ethnicity,PreviousGDM10 V1,...,BirthInjury,Dystocia,Antenatal_steroid_use,FetalJaundice,Total bilirubin,RR>60,SCBU,Cong malformation,Epidural,Spinal
0,1,114,58,73,59.4,169.6,20.650699,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
1,2,178,78,84,70.1,154.9,29.215625,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
2,3,123,62,79,64.9,157.8,26.063378,NR,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
3,4,115,68,82,67.1,164.7,24.736333,3,White,0,...,0,0,No,0,NaN,No,0,0,No,NR
4,5,116,61,92,67.5,169.9,23.383904,3,White,0,...,0,0,No,0,NaN,No,0,0,No,NR

In [ ]:
X=df[['systolicBP_V1','diastolicBP_V1','WeightinV1','BMIinV1','Age_gt_30','Vit D Deficiency']]
y=df['GDM Diagonised']

In [ ]:
X.isnull().sum()

systolicBP_V1       0
diastolicBP_V1      0
WeightinV1          0
BMIinV1             0
Age_gt_30           0
Vit D Deficiency    0
dtype: int64

In [ ]:
pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: imblearn in /usr/local/lib/python3.10/dist-packages (0.0)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.10/dist-packages (from imblearn) (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (1.10.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn->imblearn) (3.1.0)

In [ ]:
from imblearn import under_sampling, over_sampling
from collections import Counter

In [ ]:
from imblearn.under_sampling import RandomUnderSampler
rus=RandomUnderSampler(random_state=0)
X_resampled, y_resampled = rus.fit_resample(X,y)
print(sorted(Counter(y_resampled).items()),y_resampled.shape)

[('No', 74), ('Yes', 74)] (148,)

In [ ]:
df2 = pd.DataFrame(X_resampled)
df2.head()

,systolicBP_V1,diastolicBP_V1,WeightinV1,BMIinV1,Age_gt_30,Vit D Deficiency
0,111,52,79.9,28.856266,1,0
1,130,74,67.5,26.073041,0,0
2,115,56,73.4,27.025992,0,0
3,138,92,127.3,46.758494,1,0
4,126,80,67.6,24.740074,1,0

In [ ]:
imputer = KNNImputer()
imp_data = imputer.fit_transform(df2)
column_names = list(df2)
final_data = pd.DataFrame(imp_data, columns = column_names)

In [ ]:
final_data.tail()

,systolicBP_V1,diastolicBP_V1,WeightinV1,BMIinV1,Age_gt_30,Vit D Deficiency
143,142.0,88.0,64.6,24.706571,1.0,1.0
144,152.0,93.0,104.5,40.264769,1.0,0.0
145,119.0,72.0,73.3,27.724447,1.0,1.0
146,115.0,68.0,69.3,25.454545,1.0,1.0
147,138.0,63.0,94.5,38.387155,1.0,0.0

In [ ]:
X1= final_data
y = y_resampled

In [ ]:
y_resampled.tail()

143    Yes
144    Yes
145    Yes
146    Yes
147    Yes
Name: GDM Diagonised, dtype: object

In [ ]:
X1_train,X1_test,y_train,y_test = train_test_split(X1,y,test_size = 0.30,random_state = 100,stratify = y)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
# Train the logistic regression model
logmodel = LogisticRegression()
logmodel.fit(X1_train, y_train)

LogisticRegression()

In [ ]:
# Make predictions on the test set
predictions = logmodel.predict(X1_test)

In [ ]:
accuracy_score(y_test,predictions)

0.6666666666666666

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          No       0.70      0.61      0.65        23
         Yes       0.64      0.73      0.68        22

    accuracy                           0.67        45
   macro avg       0.67      0.67      0.67        45
weighted avg       0.67      0.67      0.67        45

In [ ]:
input_data = (165.0,112.0,60.6,20.407797,0,0)
def gdm_diagnosis(input_data1):
  input_data_as_numpy_array = np.asarray(input_data) #changing input data to numpy array
  input_data_reshaped = input_data_as_numpy_array.reshape(1,-1) #reshape the array as we are predicting for one instance
  prediction = logmodel.predict(input_data_reshaped)
  print(prediction)

In [ ]:
gdm_diagnosis (input_data)

['No']

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but LogisticRegression was fitted with feature names

In [ ]:
input_data = (138.0,63.0,94.5,38.387155,1.0,0.0)
def gdm_diagnosis(input_data1):
  input_data_as_numpy_array = np.asarray(input_data) #changing input data to numpy array
  input_data_reshaped = input_data_as_numpy_array.reshape(1,-1) #reshape the array as we are predicting for one instance
  prediction = logmodel.predict(input_data_reshaped)
  print(prediction)

In [ ]:
gdm_diagnosis (input_data)

['Yes']

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but LogisticRegression was fitted with feature names

In [ ]:
input_data = (115.0,68.0,69.3,25.454545,1.0,1.0)
def gdm_diagnosis(input_data1):
  input_data_as_numpy_array = np.asarray(input_data) #changing input data to numpy array
  input_data_reshaped = input_data_as_numpy_array.reshape(1,-1) #reshape the array as we are predicting for one instance
  prediction = logmodel.predict(input_data_reshaped)
  print(prediction)

In [ ]:
gdm_diagnosis (input_data)

['Yes']

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but LogisticRegression was fitted with feature names